### ISSUE TITLE
color in log file

### ISSUE THREAD

**Issue by Lavibu** [davidohana/colargulog#1]
Hi David,

I tested your module and code and the console output is in colors, but the log file is not (on my CentOS Linux).
Can you tell why?

Thanks,
Lavi

**Comment by davidohana** [comment]
The repository offers two formatters: `ColorizedArgsFormatter` and `BraceFormatStyleFormatter`. 
`ColorizedArgsFormatter` supports both `{ }` brace-style formatting and logging in colors with ANSI escape sequences.
`BraceFormatStyleFormatter` only supports {} brace-style formatting.

The example provided uses `BraceFormatStyleFormatter` for file handler in purpose so that escape codes will **not** appear in the log files. However, you can just replace it to `ColorizedArgsFormatter` and you will get colors (or at least their escape codes) in log files.

**Comment by Lavibu** [comment]
Thanks, will check it out!

**Comment by Lavibu** [comment]
Hi David,

Working like a charm. Thanks for writing it and replying back.

BR,
Lavi
